---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/decks":
    get:
      summary: Retrieve all blogs
      tags:
      - Decks
      responses:
        '200':
          description: Deck found
          content:
            application/json:
              examples:
                example_key:
                  value:
                  - game_id: PTCG
                    id: 1234-abcd
                    user_id: " 123d-adsd"
                    archetype:
                      identifier: gardevoir-ex
                    name: Psychic Elegance
  "/decks/{id}":
    get:
      summary: Retrieve a blog
      tags:
      - Decks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Decks found
          content:
            application/json:
              examples:
                example_key:
                  value:
                    game_id: PTCG
                    id: 1234-abcd
                    user_id: " 123d-adsd"
                    archetype:
                      identifier: gardevoir-ex
                    name: Psychic Elegance
        '404':
          description: Deck not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
