---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/{game_id}/decks/{deck_id}/lists":
    get:
      summary: Retrieve all the deck's lists
      tags:
      - Lists
      parameters:
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: deck_id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        required: true
        example: 'FIREBASE_ID_TOKEN: eyadadan...'
        schema:
          type: string
      - name: active
        in: query
        required: false
        description: filter for active lists
        schema:
          type: boolean
      responses:
        '401':
          description: unauthorized
        '200':
          description: Lists found
          content:
            application/json:
              examples:
                example_key:
                  value:
                  - deck_id: '1234'
                    id: '4567'
                    user_id: qweqejqe1234
                    name: Psychic Elegance
                    list_cards:
                    - set_id: BRS
                      name: Arceus VSTAR
                      set_number: '123'
                      count: 3
                      image: https://images.pokemontcg.io/swsh9/123.png
                    - set_id: BRS
                      name: Arceus V
                      set_number: '122'
                      count: 4
                      image: https://images.pokemontcg.io/swsh9/122.png
                    active: false
    post:
      summary: add a list to the deck
      tags:
      - Lists
      description: |-
        Add a list to the target deck.
        The cards argument of the body takes a split list of a usual export from your game client or online resource.
        Invalid card strings will be ignored automatically.
      parameters:
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: deck_id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        required: true
        example: 'FIREBASE_ID_TOKEN: eyadadan...'
        schema:
          type: string
      responses:
        '201':
          description: list created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                active:
                  type: boolean
                cards:
                  type: array
                  items:
                    type: string
                  example:
                  - 3 Arceus VSTAR BRS 123
                  - 3 Arceus V BRS 122
              required:
              - name
              - cards
  "/{game_id}/decks/{deck_id}/lists/{id}":
    get:
      summary: Retrieve a list
      tags:
      - Lists
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: deck_id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        required: true
        example: 'FIREBASE_ID_TOKEN: eyadadan...'
        schema:
          type: string
      responses:
        '200':
          description: List found
          content:
            application/json:
              examples:
                example_key:
                  value:
                    deck_id: '1234'
                    id: '4567'
                    user_id: qweqejqe1234
                    name: Psychic Elegance
                    list_cards:
                    - set_id: BRS
                      name: Arceus VSTAR
                      set_number: '123'
                      count: 3
                      image: https://images.pokemontcg.io/swsh9/123.png
                    - set_id: BRS
                      name: Arceus V
                      set_number: '122'
                      count: 4
                      image: https://images.pokemontcg.io/swsh9/122.png
                    active: false
        '401':
          description: unauthorized
        '404':
          description: Deck not found
    patch:
      summary: update a deck's list
      tags:
      - Lists
      parameters:
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: deck_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        required: true
        example: 'FIREBASE_ID_TOKEN: eyadadan...'
        schema:
          type: string
      responses:
        '200':
          description: list updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                active:
                  type: boolean
              required:
              - name
    delete:
      summary: delete a deck's list
      parameters:
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: deck_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        required: true
        example: 'FIREBASE_ID_TOKEN: eyadadan...'
        schema:
          type: string
      responses:
        '204':
          description: list deleted
  "/{game_id}/decks":
    get:
      summary: Retrieve all the user's decks
      tags:
      - Decks
      parameters:
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        required: true
        example: 'FIREBASE_ID_TOKEN: eyadadan...'
        schema:
          type: string
      responses:
        '401':
          description: unauthorized
        '200':
          description: Deck found
          content:
            application/json:
              examples:
                example_key:
                  value:
                  - game_id: PTCG
                    id: 1234-abcd
                    user_id: " 123d-adsd"
                    archetype_id: 9
                    name: Psychic Elegance
  "/{game_id}/decks/{id}":
    get:
      summary: Retrieve a deck
      tags:
      - Decks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        required: true
        example: 'FIREBASE_ID_TOKEN: eyadadan...'
        schema:
          type: string
      responses:
        '200':
          description: Decks found
          content:
            application/json:
              examples:
                example_key:
                  value:
                    game_id: PTCG
                    id: 1234-abcd
                    user_id: " 123d-adsd"
                    archetype_id: 9
                    name: Psychic Elegance
        '401':
          description: unauthorized
        '404':
          description: Deck not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
