---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/{game_id}/decks":
    get:
      summary: Retrieve all the user's decks
      tags:
      - Decks
      parameters:
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        schema:
          type: string
      responses:
        '401':
          description: unauthorized
        '200':
          description: Deck found
          content:
            application/json:
              examples:
                example_key:
                  value:
                  - game_id: PTCG
                    id: 1234-abcd
                    user_id: " 123d-adsd"
                    archetype:
                      identifier: gardevoir-ex
                    name: Psychic Elegance
  "/{game_id}/decks/{id}":
    get:
      summary: Retrieve a deck
      tags:
      - Decks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: game_id
        in: path
        required: true
        schema:
          type: string
      - name: HTTP_FIREBASE_ID_TOKEN
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Decks found
          content:
            application/json:
              examples:
                example_key:
                  value:
                    game_id: PTCG
                    id: 1234-abcd
                    user_id: " 123d-adsd"
                    archetype:
                      identifier: gardevoir-ex
                    name: Psychic Elegance
        '401':
          description: unauthorized
        '404':
          description: Deck not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
